### ISSUE TITLE
[1.19] blobs can be used to dupe items

### ISSUE THREAD

**Issue by crushedcan24** [mateusak/minecraft-blobs#1]
if you right click on a blob that is placed while holding an item that is not a blob, the blob will return as said item and not the blob. not only does this remove your blob, this also dupes your items. 
i've attached a video, as i'm not good with words. there is no sound on purpose.
[video demonstration](https://www.youtube.com/watch?v=ocltT624bCU).

**Comment by mateusak** [comment]
fixed, thank you
